# Generated by Django 5.1.4 on 2025-01-06 19:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("surname", models.CharField(max_length=255)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("personal_id", models.CharField(max_length=50, unique=True)),
                (
                    "user_type",
                    models.CharField(
                        choices=[("repatriate", "Repatriate"), ("mentor", "Mentor")],
                        max_length=50,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("moderator", "Moderator"),
                            ("user", "User"),
                        ],
                        default="user",
                        max_length=20,
                    ),
                ),
                ("approved", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=False)),
                ("images", models.JSONField(blank=True, default=list)),
                ("birthdate", models.DateField(blank=True, null=True)),
                ("city", models.CharField(max_length=100)),
                ("university", models.CharField(max_length=100)),
                ("field_of_study", models.CharField(max_length=100)),
                ("interests", models.JSONField(blank=True, default=list)),
                ("description", models.TextField(blank=True)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "hashed_login_code",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("login_code_expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to.",
                        related_name="api_users",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partners",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="api_users",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
        ),
    ]
