# Generated by Django 5.1.4 on 2025-01-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="personal_id",
            field=models.CharField(max_length=50),
        ),
    ]
