# Generated by Django 5.1.4 on 2025-01-06 21:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_user_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_active",
        ),
    ]
