# Generated by Django 5.1.4 on 2025-02-18 16:04

import api.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_fieldofstudy"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name_plural": "Cities"},
        ),
        migrations.AlterModelOptions(
            name="fieldofstudy",
            options={"verbose_name_plural": "Fields of Study"},
        ),
        migrations.AlterModelOptions(
            name="interest",
            options={"verbose_name_plural": "Interests"},
        ),
        migrations.AlterModelOptions(
            name="university",
            options={"verbose_name_plural": "Universities"},
        ),
        migrations.RemoveField(
            model_name="user",
            name="images",
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="fieldofstudy",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="university",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="api.city",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="field_of_study",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="api.fieldofstudy",
            ),
        ),
        migrations.RemoveField(
            model_name="user",
            name="interests",
        ),
        migrations.AlterField(
            model_name="user",
            name="university",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="api.university",
            ),
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.ImageField(upload_to=api.models.user_directory_path)),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner of the image",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="interests",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="api.interest"
            ),
        ),
    ]
