# Generated by Django 5.1.4 on 2025-02-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_user_saved_users_user_viewed_users_match_pending"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="match",
            options={"verbose_name_plural": "Matches"},
        ),
        migrations.AlterModelOptions(
            name="pending",
            options={"verbose_name_plural": "Pending"},
        ),
        migrations.AddField(
            model_name="user",
            name="sex",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="male",
                max_length=20,
            ),
        ),
    ]
