# Generated by Django 5.1.4 on 2025-03-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="is_viewed",
            field=models.BooleanField(default=False),
        ),
    ]
