# Redirect from HTTP to HTTPS
server {
    listen 80;
    server_name *.rimonim.me;
    return 301 https://$host$request_uri;
}

# Configuration for HTTPS
server {
    listen 443 ssl;
    server_name api.rimonim.me;

    ssl_certificate /app/ssl/certificate.crt;
    ssl_certificate_key /app/ssl/private_key.key;

    location / {
        proxy_pass http://backend:8000; # Backend service
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /static/ {
        alias /app/staticfiles/; # Serve static files from backend
    }

    location /media/ {
        alias /app/media/; # Serve media files from backend
    }

    error_log /var/log/nginx/api_error.log;
    access_log /var/log/nginx/api_access.log;
}

server {
    listen 443 ssl;
    server_name app.rimonim.me;

    ssl_certificate /app/ssl/certificate.crt;
    ssl_certificate_key /app/ssl/private_key.key;

    location / {
        proxy_pass http://104.248.121.235:4000; # Frontend service
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    error_log /var/log/nginx/app_error.log;
    access_log /var/log/nginx/app_access.log;
}

server {
    listen 443 ssl;
    server_name admin.rimonim.me;

    ssl_certificate /app/ssl/certificate.crt;
    ssl_certificate_key /app/ssl/private_key.key;

    # 1) If path is exactly "/", send a 302 redirect to "/admin/"
    location = / {
        return 302 /admin/;
    }

    # 2) If the path is /admin/ or /admin/something..., pass it to Django as-is
    location ^~ /admin/ {
        proxy_pass http://backend:8000;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /static/ {
        alias /app/staticfiles/;
        expires 30d;
        add_header Cache-Control "public";
    }

    location /media/ {
        alias /app/media/;
    }

    error_log /var/log/nginx/admin_error.log;
    access_log /var/log/nginx/admin_access.log;
}